### ISSUE TITLE
CKeyXML class needs enumeration functions for elements

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/ttLib#3]
CKeyXmlBranch provides FindFirstElement() which gives you the first occurrence of an element, but doesn't allow you to step through multiple elements. However, the enumeration variables should **NOT**  be stored in CKeyXmlBranch as this structure gets a copy allocated for every element, so each additional member has the size multiplied by every element. A better approach would be to add something like BeginEnumElement() and EnumElement() to CKeyXML.

**Comment by Randalphwa** [comment]
Won't work to implement via CKeyXML because it needs to parse grandchildren (and their children) -- so would have to have a stack of enum values that are pushed/popped. Instead, I've added a size_t to the structure which stores the nextChild to check, and a new FindNextElement() method that utilizes this.
