### ISSUE TITLE
ttLib: deprecate, then remove methods with same name as Windows API

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/ttLib#91]
### Description:
The caller could be either ANSI or UNICODE, which will add either a 'A' or 'W' to the end of any function or method that matches a Windows API. That's going to cause problems since only one of those variations will be created in **ttLib** and the other variation will be missing. We should stop using these names! Fortunately, there only appear to be three:

- GetFullPathName
- GetOpenFileName
- GetWindowText

We should change the name of the function in the code, and then change the header to deprecate the function and call the new name instead. Once all KeyWorks projects have been updated to replace the deprecated calls, then we can remove these entirely.

### Issue Type:
- [ ] Bug report
- [ ] Feature request
- [x] Other

**Comment by Randalphwa** [comment]
I think we got them all. The switch to using -DUNICODE as a compiler flag means that it is less likely to be a problem even if we missed on since most Windows apps also define UNICODE and as long as ttLib and the calling app expect UNICODE, it won't matter if the name gets changed since app and library will have the same name.
